### ISSUE TITLE
Besoin d'aide

### ISSUE THREAD

**Issue by fqlsex** [jabibamman/Bot-Vinted-Discord-JS#1]
Salut , j'ai vraiment besoin d'aide je comprends pas trop comment on installe ca même après avoir lu le tuto. Si tu pourrais me donner un peu plus d'aide ca serai cool merci d'avance ;)

**Comment by jabibamman** [comment]
> Salut , j'ai vraiment besoin d'aide je comprends pas trop comment on installe ca même après avoir lu le tuto. Si tu pourrais me donner un peu plus d'aide ca serai cool merci d'avance ;)

Salut ! 

Il me semble que la repo que j'utilisais pour mon bot est plus à jour pour le moment donc mon bot ne fonctionne plus 😕

Sinon il y à un autre repo que je peux te conseiller, elle n’est pas en JS mais en Python et fonctionne parfaitement.

Je l’ai monté sur un de mes serveur discord et elle fonctionne.

https://github.com/2spy/Vinted-Discord-Bot

Si tu as besoin d’aide pour l’installer ou si tu as des question hésite pas ;)

Discord : Jamessss#7426

Dans tout les cas si j’arrivais à refaire marcher mon bot je te l’indiquerais..

**Comment by fqlsex** [comment]
D'acc merci de ta réponse j'vais essayer d'installer par moi même je te contacte si j'ai besoin d'aide

**Comment by jabibamman** [comment]
> D'acc merci de ta réponse j'vais essayer d'installer par moi même je te contacte si j'ai besoin d'aide

Niquel ! 

Hésite pas, je reste disponible s'il le faut ;)
